### PR TITLE
Add metrics gathering for console_url

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Adds `console_url` to whitelist following this PR:

- https://github.com/openshift/console-operator/pull/270

For reference:

- edited `jsonnet/telemeter/metrics.jsonnet`
- ran `MAKE=make make generate-in-docker` to generate docs.

/assign @brancz @LiliC

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Updated, ran `MAKE=make make generate-in-docker`, looks more reasonable.

**Comment by benjaminapetersen** [comment]
@spadgett fyi

**Comment by spadgett** [comment]
cc @luciddreamz @smarterclayton

**Comment by LiliC** [comment]
/lgtm

Once https://github.com/openshift/telemeter/pull/240 this should get a lgtm label, if prow is clever enough :)

**Comment by benjaminapetersen** [comment]
`lgtm` made it, lets see if it figures out the `approve` as well.

**Pull request merged**
