### PR TITLE
Bug 1773246: Report cluster:virt_platform_nodes:sum to telemetry

### PR DESCRIPTION
**Pull request by smarterclayton**
This metric provides general info about whether nodes are kvm,
xen, baremetal, rhev, osp, or vmware virtualization. That helps
triage issues on clusters that have no cloud provider configured.

### CODE REVIEW

**Comment by LiliC** [comment]
/hold

Until https://github.com/openshift/cluster-monitoring-operator/pull/557/files is merged

**Comment by smarterclayton** [comment]
/hold cancel

Both are ready for next cherry-pick round

**Pull request merged**
