### PR TITLE
jsonnet/: Use local directory

### PR DESCRIPTION
**Pull request by LiliC**
Since we now run generate as part of CI, this should fix it hopefully.

cc @brancz @paulfantom

### CODE REVIEW

**Comment by squat** [comment]
Hey, what do you mean exactly by `Since we now run generate as part of CI`? We've run `make generate` as part of CI for a very long time?

**Comment by paulfantom** [comment]
@squat apparently we were running it only for 4.1. Later it wasn't automatically migrated and wasn't run on 4.2 and current master.

**Comment by squat** [comment]
@paulfantom where do you see it the generate test wasn't running on current master? And where did you fix that? It looks to me like PR https://github.com/openshift/release/pull/5338 only changed the order of the tests and the name for the non-master jobs.

**Comment by paulfantom** [comment]
We had 3 PRs in openshift/release bringing in generate step:
- https://github.com/openshift/release/pull/5336
- https://github.com/openshift/release/pull/5340
- https://github.com/openshift/release/pull/5338

First one brought back `generate`, the rest was needed to fix it as there was no rehersal job enabled.

**Comment by squat** [comment]
Hmm I see that you added the jobs to the release branches, but the generate
job was already there for master:
https://github.com/LiliC/release/blob/4ddc3e129f1394e2a0b55811f7f7a873d41b01da/ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml

No?

**Comment by paulfantom** [comment]
Yes, it was testing `master`. Sorry for confusion.

**Comment by LiliC** [comment]
We still need this change and to also backport it to 4.2 branch, from what I understand.

**Comment by squat** [comment]
OK good, that clears things up.

Regarding this change, I'm all for it as it simplifies our jsonnet config, however it is a nice-to-have that shouldn't be necessary to fix the issue in #245, no? After all testing generate on master has been working without this change. I just want to get to the bottom of fixing that PR as easily as possible.

**Comment by metalmatze** [comment]
> OK good, that clears things up.
> 
> Regarding this change, I'm all for it as it simplifies our jsonnet config, however it is a nice-to-have that shouldn't be necessary to fix the issue in #245, no? After all testing generate on master has been working without this change. I just want to get to the bottom of fixing that PR as easily as possible.

That is correct. But now that we have, I think we can simply keep it.

**Pull request merged**
