### PR TITLE
jsonnet/telemeter: Add a recording rule that captures network_type

### PR DESCRIPTION
**Pull request by smarterclayton**
Leverage knowledge about what resources are provided by a plugin
to categorize the usage of those plugins at a cluster _id level.
This is primarily accurate in late 4.6/4.7+ due to telemetry
including these resources. This categorized a significant chunk
of clusters although there are some edge cases noted.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Tested manually on prod data set, no errors in this recording rule

**Review by squat — APPROVED** [review]
/lgtm

**Comment by smarterclayton** [comment]
No bug needed because this is not in product.

/retest

**Comment by squat** [comment]
yes :/ rolling this out and an update to the telemeter-server allow-list today :+1:

**Pull request merged**
