### PR TITLE
Bug 1874389: add Ari to OWNERS

### PR DESCRIPTION
**Pull request by arilivigni**
Added arilivigni for reviewers and approvers

### CODE REVIEW

**Comment by squat** [comment]
This PR will have to wait for us to wait for us to fix the integration tests in #352

**Comment by squat** [comment]
@arilivigni we will need to rebase on top of https://github.com/openshift/telemeter/pull/353 once it merges to get the tests to pass

**Comment by squat** [comment]
/lgtm
@arilivigni you need to create a bugzilla in order to merge this PR right now. This is an artifact of the fact that this repo is constrained by the OpenShift release process. I can do that for this PR.

**Comment by squat** [comment]
/retitle Bug 1874389: add Ari to OWNERS

**Review by simonpasquier — COMMENTED** [review]
maybe it could be an opportunity to remove brancz too?

**Comment by squat** [comment]
let's keep these in discreet PRs so we can reason about them/revert things more easily. Plus, I don't want to have to re-rerun all of the e2e tests :P

**Comment by arilivigni** [comment]
@squat thanks for doing that I will be aware of that for next time.

**Pull request merged**
