### PR TITLE
test/benchmark: test goal

### PR DESCRIPTION
**Pull request by squat**
This commit adds a goal argument to the benchmark script. Now, any
benchmarking test that does not meet the specified goal will exit
non-zero.

### CODE REVIEW

**Comment by squat** [comment]
benchmarking failed due to:
```
level=error
level=error msg="Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached."
```
we'll need to retry

**Comment by paulfantom** [comment]
Tests are failing due to unrelated issue (we hit VPC limit).

**Comment by squat** [comment]
Still hitting VPC limits ):

**Comment by squat** [comment]
VPC API limits continue to be a problem. We'll need to wait for someone to clean up stale resources in AWS and then try again.

**Comment by squat** [comment]
Cluster never came up:

```
level=info msg="Waiting up to 30m0s for the cluster at https://api.ci-op-rkgx0z9x-e89bd.origin-ci-int-aws.dev.rhcloud.com:6443 to initialize..."
level=fatal msg="failed to initialize the cluster: Some cluster operators are still updating: authentication, console, monitoring"
```

**Comment by paulfantom** [comment]
let the @openshift-bot take care of flakes.

/retest

**Pull request merged**
