### PR TITLE
Bug 1803109: Backport cam_app_workload_migrations metric to release-4.2

### PR DESCRIPTION
**Pull request by djwhatle**
Follow up to https://github.com/openshift/telemeter/pull/298, backport of `cam_app_workload_migrations` metric was requested by Clayton per https://github.com/openshift/telemeter/pull/298#issuecomment-577158997

### CODE REVIEW

**Comment by djwhatle** [comment]
@s-urbaniak what needs to happen to the BZ linked to this PR before we can merge? QE has verified this functionality and commented on the BZ. 

I also see a warning message "expected Bugzilla bug 1803109 to depend on a bug in one of the following states: VERIFIED, RELEASE_PENDING, CLOSED (ERRATA), but no dependents were found", and not what the purpose of depending on another bug here is.

**Comment by lilic** [comment]
First the 4.3 PR needs to be merged and verified.

**Comment by djwhatle** [comment]
@lilic do you mean the 4.4 PR needs to be merged and verified? The original PR was targeted at 4.4, and backports were requested for 4.3 and 4.2.

Maybe you do in fact mean the 4.3 PR needs to go first, but I'm not aware of the procedure that makes that requires backporting happening in that order (backport to newer versions first).

**Comment by djwhatle** [comment]
Seems that [4.3 PR ](https://github.com/openshift/telemeter/pull/307) merge is pending, will see what is left to do here once that is in.

**Comment by s-urbaniak** [comment]
closing out as 4.2 is end of life.

**Pull request closed without merging**
