### PR TITLE
Bug 1750283: Backport bug 1749451 for whitelisting of cpu core node role metric.

### PR DESCRIPTION
**Pull request by chambridge**
Add backported metric to whitelist.

Related to:
https://github.com/openshift/cluster-monitoring-operator/pull/497

### CODE REVIEW

**Comment by squat** [comment]
@chambridge before we can accept this, we need a valid bugzilla. It looks like the one you linked is already listed as `ON_QA`.

**Comment by LiliC** [comment]
ok-to-test

**Comment by LiliC** [comment]
/lgtm

Sadly I am not in the OWNERS file in 4.1, so up to @squat or @brancz to merge.

**Comment by chambridge** [comment]
@LiliC @brancz We need one more PR to pull this change in to cluster-monitoring-operator to make this 4.1 backport complete, right?

I think @LiliC made that PR for me in 4.2, but if you want me to try for the backport just let me know.

**Comment by adelton** [comment]
I gave it a shot at https://github.com/openshift/cluster-monitoring-operator/pull/524.

**Pull request merged**
