### PR TITLE
Add trace context to telemeter

### PR DESCRIPTION
**Pull request by matej-g**
Resolves https://issues.redhat.com/browse/MON-1444

Adds tracing functionality to telemeter server and client.

The PR also updates `golangci-lint` to latest version, in order to avoid one of the linters complaining about a downstream package (`../go/pkg/mod/go.opentelemetry.io/otel/trace@v0.20.0/config.go:117:2: private redeclared (typecheck)`) on the older version of the linter.

### CODE REVIEW

**Comment by ianbillett** [comment]
@matej-g can you confirm that you receive traces when you run this? We did this for the API by running the Jaeger [all-in-one](https://www.jaegertracing.io/docs/1.26/getting-started/#all-in-one) container.

**Comment by matej-g** [comment]
> @matej-g can you confirm that you receive traces when you run this? We did this for the API by running the Jaeger [all-in-one](https://www.jaegertracing.io/docs/1.26/getting-started/#all-in-one) container.

Yes, I have tested it, I probably could have mentioned that in the description.

**Review by onprem — APPROVED** [review]
LGTM!

**Review by ianbillett — APPROVED** [review]

**Review by bwplotka — APPROVED** [review]
Good job, but OMG let's kill vendoring .... 

/lgtm

**Comment by matej-g** [comment]
Does anyone has the faintest idea why benchmark CI keeps failing? I tried running the benchmark from local machine on a test cluster and the Telemeter server pods are in a crash loop with log saying `Error: unknown flag: --forward-url`. Updating to later version of the Telemeter image seems to make it work again, but I'm wondering how did the benchmark ever worked if that's the real reason for the failure.

**Pull request merged**
