### PR TITLE
deploy: remove deploy directory

### PR DESCRIPTION
**Pull request by squat**
This commit removes the obsolete `deploy` directory. We can delete it
now that it is no longer needed by the ci-operator:
openshift/release#2214.

cc @metalmatze @kakkoyun

### CODE REVIEW

**Comment by s-urbaniak** [comment]
looks super! :ok_hand: small question though, as soon as we merge this here, api.ci will fail due to some references to `deploy/telemeter-client-openshift.yaml` as per https://github.com/openshift/release/blob/9c980ba/ci-operator/templates/cluster-launch-e2e.yaml#L132.

I guess we should make this (more or less) in lockstep with a corresponding PR in https://github.com/openshift/release.

**Comment by metalmatze** [comment]
Do we still want this @squat?

**Comment by squat** [comment]
We need to do a quick dig to see if it is still being used in CI as mentioned in https://github.com/openshift/telemeter/pull/48#issuecomment-429855868. Could you TAL?

**Comment by metalmatze** [comment]
I can't find anything related to Telemeter in this file. https://github.com/openshift/release/blob/1ae6f6dc7ad243f1b860b133d6a122e14c269d46/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml

**Comment by squat** [comment]
This can now safely be removed as the ci-operator no longer depends on it. @metalmatze

**Comment by squat** [comment]
cc @kakkoyun

**Pull request merged**
