### PR TITLE
jsonnet/telemeter: elide prometheus_replica label

### PR DESCRIPTION
**Pull request by s-urbaniak**
Depends on #146 to be merged first

cc @squat

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Some points also summarizing offline discussion with @squat :
- Consolidated mutation (transformers) package alongside with all the other manipulative metrics functions
- single-source-of-truth is still telemeter-server for collected metrics, if we move eliding to the prometheus scrape config, we have split mutation responsibilities for those metrics

I'll leave the final word to you @squat but given the low implementation complexity, I'd still leave this implementation in place.

**Comment by s-urbaniak** [comment]
bump @squat as #146 is merged

**Comment by cben** [comment]
https://github.com/openshift/telemeter/blob/master/docs/sample-metrics.md and https://github.com/openshift/telemeter/blob/master/test/timeseries.txt still contain this label (valued `prometheus_replica="prometheus-k8s-0"` everywhere).
Do they represent data before eliding, or after and should be updated?

**Comment by squat** [comment]
These are out of date and need to be updated :) thanks for pointing it out

**Pull request merged**
