### PR TITLE
Dockerfile: update to Go 1.13

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by squat** [comment]
This will require bumping our ksonnet version to v4 , fixing resulting inconsistencies, and some testing. I can take care of that

**Comment by metalmatze** [comment]
I am not sure if we can switch to StatefulSet `apps/v1` yet as I think it wasn't available on Kubernetes 1.11 yet... :roll_eyes:

**Comment by LiliC** [comment]
> I am not sure if we can switch to StatefulSet apps/v1 yet as I think it wasn't available on Kubernetes 1.11 yet... 🙄

This only changes telemeter for 4.4 openshift version, not sure how does that effect k8s 1.11 that was shipped in openshift 3.11?

**Comment by squat** [comment]
this was only causing errors on the benchmark test. so we bumped the API version on those manifests, not the actual server manifests used in prod. https://github.com/openshift/telemeter/pull/289

we should be able to rebase this PR and re-run now

**Pull request merged**
