### PR TITLE
This patch adds metrics that will be used to report use of CPU, memory

### PR DESCRIPTION
**Pull request by nimrodshn**
A rebase of #114 onto master.

cc: @jhernand @yaacov @kbsingh @oourfali @brancz @squat

### CODE REVIEW

**Comment by nimrodshn** [comment]
@brancz @mxinden I am not quit sure why `ci/prow/generate` is failing can you help me?

**Comment by squat** [comment]
@nimrodshn the generate test is failing because the generated secret values do not include `{__name__="cluster_version_available_updates"}`. It seems that you didn't regenerate the manifests after rebasing on https://github.com/openshift/telemeter/pull/129. Can you please rebase and re-generate.

Separately, as mentioned in https://github.com/openshift/telemeter/pull/114#issuecomment-467521346, we do not want to add these metrics like this, but as aggregated metrics. Are these the aggregated recording rule names?

**Comment by brancz** [comment]
I agreed with kB that we’re taking this over.

**Comment by nimrodshn** [comment]
Closing as there is no intention to add these metrics.

**Pull request closed without merging**
