### PR TITLE
test: use UP for querying in integration test

### PR DESCRIPTION
**Pull request by squat**
This commit updates the telemter v2 integration test to use UP for the
querying functionality, rather than using a bash loop.

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

cc @kakkoyun

### CODE REVIEW

**Comment by squat** [comment]
depends on https://github.com/openshift/telemeter/pull/293

**Comment by squat** [comment]
/hold
Wait for #293

**Comment by kakkoyun** [comment]
🎉

**Pull request merged**
