### PR TITLE
OCPBUGS-30832: bump Go 1.21

### PR DESCRIPTION
**Pull request by marioferh**
Supersedes https://github.com/openshift/telemeter/pull/522

### CODE REVIEW

**Comment by marioferh** [comment]
/hold
Waiting for art bot?

**Comment by simonpasquier** [comment]
you need a change to .ci-operator.yaml  too
https://github.com/openshift/telemeter/pull/522/files#diff-4d5699538541ad6da5f6ae79150b49a432b610f4cba488cec683ac9dd00b18d2

**Comment by marioferh** [comment]
Waiting for https://github.com/openshift/telemeter/pull/523 after some issues with linter

**Comment by simonpasquier** [comment]
/retitle OCPBUGS-30832: bump Go 1.21

another option would be to bump golangci-lint in this PR directly.

**Pull request merged**
