### PR TITLE
insightsclient_request_send_total metric from insights-operator 

### PR DESCRIPTION
**Pull request by SamuelStuchly**
Added a insightsclient_request_send metric from insights-operator. The metric can be found in  [openshift/insights-operator](https://github.com/openshift/insights-operator) repository in [insightsclient.go](https://github.com/openshift/insights-operator/blob/master/pkg/insights/insightsclient/insightsclient.go).

### CODE REVIEW

**Comment by brancz** [comment]
Is this a counter? If so it violates the instrumentation guidelines. It should have an _total suffix.

**Comment by SamuelStuchly** [comment]
> Is this a counter? If so it violates the instrumentation guidelines. It should have an _total suffix.

The metric is type gauge, but yes it seems to be serving as a counter. I assume the _total suffix is supposed to be on any metric that serves as a counter not just of type counter, so therefore i will add it. Please correct me if I am wrong.

**Comment by brancz** [comment]
> The metric is type gauge, but yes it seems to be serving as a counter. I assume the _total suffix is supposed to be on any metric that serves as a counter not just of type counter, so therefore i will add it. Please correct me if I am wrong.

If it behaves like a counter, then why not define it as a counter? If it's not a counter then it shouldn't have the suffix.

**Comment by SamuelStuchly** [comment]
> > The metric is type gauge, but yes it seems to be serving as a counter. I assume the _total suffix is supposed to be on any metric that serves as a counter not just of type counter, so therefore i will add it. Please correct me if I am wrong.
> 
> If it behaves like a counter, then why not define it as a counter? If it's not a counter then it shouldn't have the suffix.

I am not sure, i did not write the code. But since there doesnt seem to be a reason for metric being gauge it will be changed to counter and therefore keep the _total suffix. I will set this PR as WIP until it is ready.

**Comment by SamuelStuchly** [comment]
Changes with the insightsclient_request_send_total metric have been approved and are in process of being merged into openshift/insights-operator. So it is ready to be added here.

**Comment by brancz** [comment]
Happy to approve once we see a cluster that is successfully collecting this metric. Could you share a screenshot of the Prometheus UI querying this metric in a live cluster?

**Comment by SamuelStuchly** [comment]
Sorry it took so long, we ran into some difficulties because of changes to the api that we were unaware of. It is now ready. Here is a screenshot : https://raw.githubusercontent.com/SamuelStuchly/metrics_screenshot/master/Screenshot%20from%202019-11-12%2018-21-17.png

**Comment by LiliC** [comment]
You need for regenerate the manifests, run `make generate-in-docker` in root dir of the project.

**Comment by SamuelStuchly** [comment]
@brancz can you please look at this ?

> You need for regenerate the manifests, run `make generate-in-docker` in root dir of the project.

**Comment by LiliC** [comment]
@SamuelStuchly you need to run that make target in the root of this repo locally, and the tests will pass. :) @brancz will tell you the same thing ;) That will generate the manifests:

```
make generate-in-docker
```

But I think since this is past code freeze, we can't merge this for 4.3 anyways, unless you have a valid bugzilla.

/hold

**Comment by SamuelStuchly** [comment]
@LiliC  Could you please explain a little better what i am supposed to do, I dont see how me running your repo locally, that i added one metric name into, will do anything. Am i supposed to run make target and push changes to this PR ? 
(cc:@tisnik,@inecas)

**Comment by brancz** [comment]
> Am i supposed to run make target and push changes to this PR ?

Yes, run `make generate-in-docker` and commit the changes to this PR, just like @LiliC already said.

**Comment by SamuelStuchly** [comment]
I tried to run it, based on README. This is the output, can you give me some guidance please ? 
```
make generate-in-docker
find: ‘./benchmark’: No such file or directory
docker run --rm -u="1000:1000" -v "/home/samuel_RH/.cache/go-build:/.cache/go-build" -v "/home/samuel_RH/RH_projects/telemeter:/go/src/github.com/openshift/telemeter:Z" -w "/go/src/github.com/openshift/telemeter" -e GO111MODULE=on quay.io/coreos/jsonnet-ci make  generate
find: './benchmark': No such file or directory
cd jsonnet && jb install
fatal: unable to access 'https://github.com/ksonnet/ksonnet-lib/': Could not resolve host: github.com
archive install failed: Get https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz: dial tcp: i/o timeout
retrying with git...
Initialized empty Git repository in /go/src/github.com/openshift/telemeter/jsonnet/vendor/.tmp/jsonnetpkg-ksonnet-0d2f82676817bbf9e4acf6495b2090205f323b9f967867756/.git/
fatal: unable to access 'https://github.com/ksonnet/ksonnet-lib/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/ksonnet/ksonnet-lib/': Could not resolve host: github.com
jb: error: failed to install packages: downloading: exit status 128
make: *** [Makefile:84: jsonnet/jsonnetfile.lock.json] Error 1
make: *** [Makefile:81: generate-in-docker] Error 2
```

**Comment by SamuelStuchly** [comment]
@brancz

**Comment by LiliC** [comment]
/hold cancel

FYI: this is merging it in 4.4 only

**Pull request merged**
