### PR TITLE
Metrics to collect the usage of multus cni plugin for sriov and all n…

### PR DESCRIPTION
**Pull request by aneeshkp**
…etwork types
This PR is for collecting usage of multus CNI plugin labeled by networks.
These are the related PR's to expose metrics to Prometheus from the instance
openshift/cluster-network-operator#377
(Yet to be merged)

Note: closed old  [PR](https://github.com/openshift/telemeter/pull/259) and opened this

### CODE REVIEW

**Comment by aneeshkp** [comment]
@brancz 
Made changes as you suggested . I had to close [old PR](https://github.com/openshift/telemeter/pull/259)
all_instances
record_rules_forinstance_up

**Comment by s-urbaniak** [comment]
/hold

let's hold this until https://github.com/openshift/cluster-network-operator/pull/377 is merged.

**Comment by s-urbaniak** [comment]
/approve
i believe all the comments have been addressed, but leaving a 3rd and 4th eye to @brancz / @squat

**Comment by aneeshkp** [comment]
@s-urbaniak  https://github.com/openshift/cluster-network-operator/pull/377 is successfully merged. Can this be merged?

**Comment by s-urbaniak** [comment]
@aneeshkp looks good :+1: please follow https://url.corp.redhat.com/730aaa1 to add a subsequent PR against cluster monitoring operator.

**Comment by aneeshkp** [comment]
@s-urbaniak Thanks,  I will follow the next step for  PR against cluster monitoring operator.

**Pull request merged**
