### PR TITLE
test: Use specific version of UP to fix broken integration tests

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR fixes integration tests that are broken after a dependency update.
The pipeline now uses a fixed version of the tool.

### CODE REVIEW

**Comment by squat** [comment]
/lgtm
This is a temporary fix until we can get go 1.13 working in master, at which point we’ll switch to tools.go

**Comment by kakkoyun** [comment]
xref: https://github.com/openshift/telemeter/pull/291 and https://github.com/openshift/telemeter/pull/293

**Pull request merged**
