### PR TITLE
OCPBUGS-34830: fix issuer check during JWT authentication 4.14

### PR DESCRIPTION
**Pull request by thibaultmg**

### CODE REVIEW

**Comment by juzhao** [comment]
ci/prow/lint failed
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_telemeter/539/pull-ci-openshift-telemeter-release-4.14-lint/1805455243253649408
```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for \"gopkg.in/square/go-jose.v2/jwt\"\n\n"
make: *** [Makefile:138: lint] Error 3 
```

ci/prow/unit failed
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_telemeter/539/pull-ci-openshift-telemeter-release-4.14-unit/1805455243362701312
```
 # github.com/openshift/telemeter/pkg/authorize/jwt
pkg/authorize/jwt/client_authorizer_test.go:15:2: cannot query module due to -mod=vendor
FAIL	github.com/openshift/telemeter/pkg/authorize/jwt [setup failed] 
```

ci/prow/vendor failed
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_telemeter/539/pull-ci-openshift-telemeter-release-4.14-vendor/1805455243337535488
```
 github.com/openshift/telemeter/pkg/authorize/jwt tested by
	github.com/openshift/telemeter/pkg/authorize/jwt.test imports
	gopkg.in/square/go-jose.v2/jwt: no required module provides package gopkg.in/square/go-jose.v2/jwt; to add it:
	go get gopkg.in/square/go-jose.v2/jwt
make: *** [Makefile:86: vendor] Error 1 
```

maybe the PR need rebase?

**Comment by simonpasquier** [comment]
@thibaultmg this needs a rebase.

**Pull request merged**
