### PR TITLE
Capture total CAM app workload migrations by migration state.

### PR DESCRIPTION
**Pull request by djwhatle**
Add metric gathering for `cam_app_workload_migration_total`

- Metric was originally added to mig-controller in https://github.com/fusor/mig-controller/pull/379 , got feedback from Clayton
- Metric name was adjusted after consulting with @LiliC and @smarterclayton in https://github.com/fusor/mig-controller/pull/385
- Metric was added to mig-operator in https://github.com/fusor/mig-operator/pull/193

Metric is intended to help us understand at a high level how customers are using app workload migration tooling (CAM) to move apps and PV data between OpenShift clusters, especially when moving from OpenShift 3->4.

### CODE REVIEW

**Comment by LiliC** [comment]
/hold

Had a couple of questions first.

**Comment by LiliC** [comment]
/hold

We may want to change the _total suffix as its a gauge, and that suffix is reserved for counters only. Sorry for only catching this now!

**Comment by djwhatle** [comment]
@LiliC changed metric name in this PR following suggested name change getting merged to mig-controller https://github.com/fusor/mig-controller/commit/ba5feb7b519213a3435c3ecaefd4bf8d0895c0cc

**Comment by LiliC** [comment]
I will take care of getting this into the other repos as I want to update the docs on it.

**Comment by LiliC** [comment]
But you need to do the bugzilla and PRs for 4.3 and 4.2 as Clayton suggested that this needs to be backported. The same docs as they stand apply for that. Let me know if you have any questions.

**Pull request merged**
