### PR TITLE
Bug 1818806: jsonnet/telemeter: set cpu requests, unset limits

### PR DESCRIPTION
**Pull request by simonpasquier**
This is a backport of #320.

cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by simonpasquier** [comment]
@bparees could you set `cherry-pick-approved` on this change? As Serg [wrote](https://github.com/openshift/telemeter/pull/320#issuecomment-604635871) in the PR for the `release-4.4` branch, this change is only touching the jsonnet code and the "real" work will happen in github.com/openshift/cluster-monitoring where we'll update the vendored version of the jsonnet library.

**Comment by bparees** [comment]
> @bparees could you set cherry-pick-approved on this change?

I cannot, that's a patch manager responsibility(and i'm not patch manager this week).  You'll have to wait for the patch manager of the week to review+approve it(or explain why they did not/will not).  Should happen today.

**Comment by simonpasquier** [comment]
Thanks for the quick and clear explanation!

**Pull request merged**
